### ISSUE TITLE
Ransac fails after a single iteration

### ISSUE THREAD

**Issue by dimy93** [peterkovesi/ImageProjectiveGeometry.jl#13]
https://github.com/peterkovesi/ImageProjectiveGeometry.jl/blob/fb35a17813e4e87c4fc0dc705b0b9886c03ce3bb/src/ransac.jl#L181

First I want to point out that I found the bug in 2009's version of the Matlab version of this piece of code but looking at the code seems that the relevant part that causes the bug seems unchanged. The problem is with the initialization of bestscore to 0. If we get really unlucky and in the first ransac try and get 0 inliers with current code we don't enter the if on line 181 and that results to N being left to 1 and ransac exiting immediately. I know that this can be avoided if a well designed distfn is used but I wanted to still point it out in case you are willing to fix it both here and in the Matlab version.

Thanks,
Dimitar

**Comment by peterkovesi** [comment]
Thank you for pointing this problem out and my apologies for having left the bug unfixed.  I believe I have fixed the problem by initialising N, the number of required trials to `maxTrials` rather than 1.  Testing this on an example with the distance threshold `t` set to 0 to ensure no inliers results in the code performing `maxTrials` iterations in an attempt to find a solution.  If you install the current master you should have the updated code.  (I have also corrected the version on my MATLAB site)

**Comment by dimy93** [comment]
That's a proper fix. Thanks for the fast response :)
