### ISSUE TITLE
broken distortion in imagept2plane

### ISSUE THREAD

**Issue by mapclyps** [peterkovesi/ImageProjectiveGeometry.jl#31]
From the documentation, I got that `imagept2plane` should reverse `cameraproject`. This also works fine as long as all distortion coefficients are zero.

After trying around a bit more, I found also a comment in the tests regarding this.

https://github.com/peterkovesi/ImageProjectiveGeometry.jl/blob/e1d2ad2a08331d652a4580a757e84e95042c2b5b/test/test_projective.jl#L34-L41

To my understanding, the `imagept2plane` could use need a more refined method to model the inverse of the distortion. I am not an expert in this, but I [read something](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4934233/) about an iterative method or modified coefficients. I just tried the iterative method, and it was working. It is slowing down the function quite a bit, but at least it gives the correct results. 

I could contribute this modification if there is interest

**Comment by peterkovesi** [comment]
I wrote that code some time ago and, now that I see that comment, I do remember being a bit puzzled why the reconstruction was not correct when there was lens distortion.  I thought my inverse lens distortion code was, at least, approximately OK but clearly something was not right. However, at the time I did not track down where the problem was. 

You are most welcome to make a PR with your iterative method however, if possible, it would be nice to preserve the speed if there is no distortion present.

That's an interesting paper that you linked to

Cheers
